version: '3'

services:
  postgres-db-fornecedores:
    container_name: postgres-db-fornecedores
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "fornecedores"
      TZ: "America/Sao_Paulo"
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
    networks:
      - docker-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "1.0"
        reservations:
          memory: 1024M
          cpus: "1.0"

  fornecedores-api:
    container_name: fornecedores-api
    image: wesleyeduardodev/fornecedores-api:latest
    environment:
      SERVER_PORT: 3000
      SPRING_PROFILES_ACTIVE: prod
      TZ: "America/Sao_Paulo"
    ports:
      - "80:3000"
    depends_on:
      - postgres-db-fornecedores
    networks:
      - docker-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "1.0"
        reservations:
          memory: 1024M
          cpus: "1.0"

networks:
  docker-network:
    driver: bridge