version: '3'

services:
  postgres-db-fornecedores:
    container_name: postgres-db-fornecedores
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "fornecedores"
      TZ: "America/Sao_Paulo"
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge