version: '3'

services:
  postgres-db-fornecedores:
    container_name: postgres-db-fornecedores
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "fornecedores"
      TZ: "America/Sao_Paulo"
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
    networks:
      - docker-network
    restart: always

  fornecedores-api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: fornecedores-api
    image: wesleyeduardodev/fornecedores-api:latest
    environment:
      SERVER_PORT: 3000
      SPRING_PROFILES_ACTIVE: dev
      TZ: "America/Sao_Paulo"
    ports:
      - "81:3000"
    depends_on:
      - postgres-db-fornecedores
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge