version: '3'

services:

  postgres-db-fornecedores:
    container_name: postgres-db-fornecedores
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "fornecedores"
      TZ: "America/Sao_Paulo"
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
    networks:
      - docker-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: "0.25"
        reservations:
          memory: 200M
          cpus: "0.25"

  postgres-db-pedidos:
    container_name: postgres-db-pedidos
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "pedidos"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
      #volumes:
      #-  ./postgres-data:/var/lib/postgresql/data
    networks:
      - docker-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: "0.25"
        reservations:
          memory: 200M
          cpus: "0.25"

  fornecedores-api:
    build:
      context: ../fornecedores-api
      dockerfile: Dockerfile.prod
    container_name: fornecedores-api
    image: wesleyeduardodev/fornecedores-api:latest
    environment:
      SERVER_PORT: 3001
      SPRING_PROFILES_ACTIVE: prod
      TZ: "America/Sao_Paulo"
    ports:
      - "81:3001"
    depends_on:
      - postgres-db-fornecedores
    networks:
      - docker-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 250M
          cpus: "0.25"
        reservations:
          memory: 250M
          cpus: "0.25"

  pedidos-api:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: pedidos-api
    image: wesleyeduardodev/pedidos-api:latest
    environment:
      SERVER_PORT: 3000
      SPRING_PROFILES_ACTIVE: prod
      TZ: "America/Sao_Paulo"
    ports:
      - "80:3000"
    depends_on:
      - postgres-db-fornecedores
      - postgres-db-pedidos
      - fornecedores-api
    networks:
      - docker-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 350M
          cpus: "0.25"
        reservations:
          memory: 350M
          cpus: "0.25"

networks:
  docker-network:
    driver: bridge