version: '3'

services:

  postgres-db:
    container_name: postgres-db
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "desafio"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    networks:
      - docker-network
    restart: always

  fornecedores-api:
    container_name: fornecedores-api
    image: wesleyeduardodev/fornecedores-api:latest
    environment:
      SERVER_PORT: 3001
      SPRING_PROFILES_ACTIVE: prod
      TZ: "America/Sao_Paulo"
    ports:
      - "81:3001"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    restart: always

  pedidos-api:
    container_name: pedidos-api
    image: wesleyeduardodev/pedidos-api:latest
    environment:
      SERVER_PORT: 3000
      SPRING_PROFILES_ACTIVE: prod
      TZ: "America/Sao_Paulo"
    ports:
      - "80:3000"
    depends_on:
      - postgres-db
      - fornecedores-api
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge