server:
  port: 81

spring:

  datasource:
    username: user
    url: jdbc:mysql://localhost:3306/fornecedores
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  sql:
    init:
      mode: always


  #fornecedor:
  #  api:
  #   user: admin
  #  password: admin

springdoc:
  swagger-ui:
    operations-sorter: method
    path: "/fornecedores-api/swagger-ui.html"
