server:
  port: ${SERVER_PORT}

spring:
  application:
    name: "fornecedores-api"

  config:
    activate:
      on-profile:
        - prod

  datasource:
    username: postgres
    url: jdbc:postgresql://postgres-db-fornecedores:5433/fornecedores
    password: root
    driver-class-name: "org.postgresql.Driver"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    operations-sorter: method
    path: "/fornecedores-api/swagger-ui.html"
