server:
  port: 81

spring:

  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5433/fornecedores
    password: root
    driver-class-name: "org.postgresql.Driver"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


  #fornecedor:
  #  api:
  #   user: admin
  #  password: admin

springdoc:
  swagger-ui:
    operations-sorter: method
    path: "/fornecedores-api/swagger-ui.html"
